# Program settings
rngSeed: 1234
logLevel: 2
timerLevel: 3

# Time stepping
dt: 1.0
timeSnap: 1.0
timeTotal: 100.0

# Simulation box
simBoxLow: [0.0, 0.0, 0.0]
simBoxHigh: [10.0, 10.0, 10.0]
simBoxPBC: [true, true, true] # Periodic boundary condition
monolayer: false # Hold in a plane

# Initialization box
initBoxLow: [0.0, 0.0, 0.0]
initBoxHigh: [10.0, 10.0, 10.0]
initPreSteps: 100 # Number of steps to run before the first snapshot

# Physical settings
viscosity: 1.0
KBT: -0.00411 #pN.um, any negative value means no thermal noise

# Collision resolver (LCP) settings
conMaxIte: 10000
conResTol: 1e-5
conSolverChoice: 0

# Sylinder settings
sylinderColBuf: 0.2 # um Recommended to be the same as sylinderDiameter
sylinderDiameterColRatio: 1.0
sylinderLengthColRatio: 1.0

# Overwritten if TubuleInitial.dat is specified
sylinderLength: 1.0 # um
sylinderLengthSigma: 0 # logNormal distribution
sylinderDiameter: 0.2 # um
sylinderFixed: false # Hold sylinders in place
sylinderNumber: 1000 # Number of sylinders
initOrient: [1, 0, 0] # components < -1  or > 1 are randomly assigned
